export { default as Hero } from './Hero'
export { default as Task } from './Task'
export { default as News } from './News'
export { default as Events } from './Events'
export { default as Updates } from './Updates'
export { default as Birthdays } from './Birthdays'
export { default as QuickLinks } from './QuickLinks'
